[package]
name = "selmita"
version = "1.0.0"
edition = "2021"

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus", branch = "main" } # waiting for release with full rb-sys backend

[lib]
name = "selmita"
crate-type = ["cdylib"]
